#pragma config(Sensor, dgtl1,  startSwitch,    sensorTouch)
#pragma config(Sensor, dgtl4,  reflectiveFL,   sensorDigitalIn)
#pragma config(Sensor, dgtl5,  reflectiveFR,   sensorDigitalIn)
#pragma config(Sensor, dgtl6,  reflectiveBL,   sensorDigitalIn)
#pragma config(Sensor, dgtl7,  reflectiveBR,   sensorDigitalIn)
#pragma config(Motor,  port4,           leftWheel,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           rightWheel,    tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//---------------------------function definitions----------------------------------
void differnetial_drive (int leftLevel, int rightLevel);
void wait_for_on();
//---------------------------tasks definitions------=------------------------------
void checking_reflective_sensor();

/*--- differential drive -----
direction: 1 (forward), -1 (backward)
speedMode: 0(stop), 1(1/4 speed),2,3,4(max speed), minus/plus sign
*/
void differnetial_drive(int leftLevel, int rightLevel)
{
	int voltageRight;
	int voltageLeft;

	voltageLeft = leftLevel*30;
	voltageRight = rightLevel*30;

	motor[rightWheel] = -voltageRight;
	motor[leftWheel]  = voltageLeft;
}



void wait_for_on()
{
	while(SensorValue[startSwitch] == 0)
	{
		// while start switch not activated, wait inside the loop
	}
	checking_reflective_sensor();

}


void checking_reflective_sensor()
{
	while (true)
	{
		if (SensorValue[reflectiveBR] == 0 || SensorValue[reflectiveBL] == 0)
	  {
	     differnetial_drive(3,3);
	     wait1Msec(400);
	  	 differnetial_drive(-2.5,2.5);
	  	 wait1Msec(400);
	  }
	  else if (SensorValue[reflectiveFL] == 0 || SensorValue[reflectiveFR] == 0 )
	  {
	  	 differnetial_drive(-3,-3);
	  	 wait1Msec(400);
	  	 differnetial_drive(2.5,-2.5);
	  	 wait1Msec(400);
	  }
	  else if (SensorValue[reflectiveBR] != 0 && SensorValue[reflectiveFR] != 0 && SensorValue[reflectiveFL] != 0 && SensorValue[reflectiveBL] != 0)
		{
				differnetial_drive(1,1);
				wait1Msec(50);
	  }
	  else if (SensorValue[startSwitch] == 0)
	  {
		   differnetial_drive(0,0);
		   wait1Msec(50);
		   break;
    }
	}

}

task main()
{
  wait_for_on();
  while(true)
  {
  	wait1Msec(1);
    // Keep the program alive
  }
}
