#pragma config(Sensor, dgtl1,  startSwitch,    sensorTouch)
#pragma config(Sensor, dgtl2,  reflectiveFL,   sensorDigitalIn)
#pragma config(Sensor, dgtl3,  reflectiveFR,   sensorDigitalIn)
#pragma config(Sensor, dgtl4,  reflectiveBL,   sensorDigitalIn)
#pragma config(Sensor, dgtl5,  reflectiveBR,   sensorDigitalIn)
#pragma config(Motor,  port2,           leftWheel,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           rightWheel,    tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//---------------------------function definitions----------------------------------
void differnetial_drive (int leftLevel, int rightLevel);
void wait_for_on();
//---------------------------tasks definitions------=------------------------------
//---------------------------tasks definitions-------------------------------------
task checking_reflective_sensor();

/*--- differential drive -----
direction: 1 (forward), -1 (backward)
speedMode: 0(stop), 1(1/4 speed),2,3,4(max speed), minus/plus sign
*/
void differnetial_drive(int leftLevel, int rightLevel)
{
	int voltageRight;
	int voltageLeft;

	voltageLeft = leftLevel*30;
	voltageRight = rightLevel*30;

	motor[rightWheel] = -voltageRight;
	motor[leftWheel]  = voltageLeft;
}



void wait_for_on()
{
	while(SensorValue[startSwitch] == 0)
	{
		// while start switch not activated, wait inside the loop
	}
	startTask(checking_reflective_sensor);

}


task checking_reflective_sensor()
{
	if (SensorValue[reflectiveBR] != 0 && SensorValue[reflectiveFR] != 0 && SensorValue[reflectiveFL] != 0 && SensorValue[reflectiveBL] != 0)
	{
			differnetial_drive(1,1);
  }
  else if (SensorValue[reflectiveFR] == 0 && SensorValue[reflectiveFL] == 0)
  {
  	 differnetial_drive(1,-1); // rotate 180 degree
  	 wait1Msec(3000);
  }
  else if (SensorValue[reflectiveBL] == 0 && SensorValue[reflectiveBR] == 0)
  {
  	 differnetial_drive(0,0); // stop
  	 wait1Msec(1000);
  }
  else if (SensorValue[reflectiveFL])
  {
  	 differnetial_drive(1,-1); // turn right 60 degree
  	 wait1Msec(1000);
  }
  else if (SensorValue[reflectiveFR])
  {
  	 differnetial_drive(-1,1); // turn left 60 degree
  	 wait1Msec(1000);
  }
  else if (SensorValue[reflectiveBR])
  {
  	 differnetial_drive(-1,1); // turn left 30 degree
  	 wait1Msec(1000);
  }
  else if (SensorValue[reflectiveBL])
  {
  	 differnetial_drive(1,-1); // turn right 30 degree
  	 wait1Msec(1000);
  }

}

task main()
{
  wait_for_on();

}
