#pragma config(Motor,  port2,           servoMotor,    tmotorServoStandard, openLoop)
#pragma config(Motor,  port4,           leftWheel,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           rightWheel,    tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task main()
{
   	motor[servoMotor] = 127;       // Set 'servoMotor' to position -127 (negative end of range)
		wait1Msec(500);

		//motor[servoMotor] = 30;       // Set 'servoMotor' to position -127 (negative end of range)
		//wait1Msec(500);

		//motor[servoMotor] = 30;       // Set 'servoMotor' to position -127 (negative end of range)
		//wait1Msec(500);



}
