#pragma config(Sensor, dgtl1,  masterSwitch,   sensorTouch)
#pragma config(Motor,  port4,           leftWheel,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           rightWheel,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port2,           servoLeft,     tmotorServoStandard, openLoop)
#pragma config(Motor,  port3,           servoRight,    tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//-127: fully backward
//MAGNITUDE proportional to POSITION and SPEED
#define ANGLE_INIT 0	//test angles
#define ANGLE_CATCH -30 //test angles -126
#define ANGLE_SECURE 0 //test angles
#define ANGLE_RELEASE 60
#define DELAY_CATCH 1
#define DELAY_RELEASE 1000


void wait_for_on();


void differnetial_drive(float leftLevel, float rightLevel)
{
	float voltageRight;
	float voltageLeft;

	voltageLeft = leftLevel*30;
	voltageRight = rightLevel*30;

	motor[rightWheel] = -voltageRight;
	motor[leftWheel]  = voltageLeft;
}

/* Catch ball
@param return true if sucessful, false if unsucessful
*/

void catch_ball()	//can change to bool when include checking ball
{
    motor[servoRight] = 40;       // Set 'servoMotor' to position -127 (negative end of range)
		//wait1Msec(500);

		motor[servoLeft] = -50;       // Set 'servoMotor' to position -127 (negative end of range)
		wait1Msec(550);
}


void release_ball()
{
	  motor[servoRight] = -35;       // Set 'servoMotor' to position -127 (negative end of range)
		//wait1Msec(500);

		motor[servoLeft] = 60;       // Set 'servoMotor' to position -127 (negative end of range)
		wait1Msec(1000);
}


//void reset_servo()
//{
//	servo_to_angle(servoLeft,0,DELAY_CATCH);
//	servo_to_angle(servoRight,0,DELAY_CATCH);
//}

void wait_for_on()
{
	while(SensorValue(masterSwitch)==0)
	{
		//wait
	}
}

task main()
{
	wait_for_on();
	catch_ball();

	clearTimer(T1);
	while(time1[T1]<800) // search for 1.6 seconds (level 1),,, level2 -- 0.8 sec
	{
     differnetial_drive(1, 1); // rotate CCW
	}

	clearTimer(T1);
	while(time1[T1]<800)
	{

			differnetial_drive(-1, -1);    //rotate CW
	}


	release_ball();
}
