#pragma config(Sensor, in2,    shortDistanceSensor, sensorAnalog)
#pragma config(Sensor, in3,    longDistanceSensor, sensorAnalog)
#pragma config(Sensor, dgtl3,  startSwitch,    sensorTouch)
#pragma config(Motor,  port4,           leftWheel,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           rightWheel,    tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
This program is for testing the motor speed.
It will be used for experiment purpose only.
Functionality:
- After press the start switch, the vehicle will start to move
- record the distance of its moving and divided by the travelling time --> get the speed mm/s
- The recorded speed will be used and analyzed for competition strategy design.
- We will also see the drift for the robot moving in straight line.
---(should not drift too much)
*/

//---------------------------function definitions----------------------------------
void wait_for_on();
void differnetial_drive (float leftLevel, float rightLevel);
//---------------------------tasks definitions------=------------------------------


/*--- differential drive -----
direction: 1 (forward), -1 (backward)
speedMode: 0(stop), 1(1/4 speed),2,3,4(max speed), minus/plus sign
*/
void differnetial_drive(float leftLevel, float rightLevel)
{
	float voltageRight;
	float voltageLeft;

	voltageLeft = leftLevel*30;
	voltageRight = rightLevel*30;

	motor[rightWheel] = -voltageRight;
	motor[leftWheel]  = voltageLeft;
}



void wait_for_on()
{
	while(SensorValue[longDistanceSensor] < 300)
	{
		differnetial_drive(-2,2);
  }

  clearTimer(T1);
	while(time1[T1]<200)
	{

			differnetial_drive(2, -2);    //rotate CW
	}

  //differnetial_drive(0,0);

  while(SensorValue[longDistanceSensor] < 200)
	{
		differnetial_drive(1,1);
  }
  differnetial_drive(0,0);


}


/*------------------------------------------------------------------------------------------------------------------*/
/*------------------------------------Tasks (Parallel-runing programs (threads))------------------------------------*/
/*------------------------------------------------------------------------------------------------------------------*/


// main task
task main()
{
	wait_for_on();

}//end of main
