#pragma config(Sensor, in5,    gripperBumper, sensorAnalog)
#pragma config(Sensor, in3,    LeftDistanceSensor, sensorAnalog)
#pragma config(Sensor, in4,    enemyDistanceSensor, sensorAnalog)
#pragma config(Sensor, dgtl3,  BackRightSwitch, sensorTouch)
#pragma config(Sensor, dgtl2,  BackLeftSwitch, sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Opens Debug Stream Window automatically
#pragma DebuggerWindows("DebugStream")


task main()
{

  //Clears Debug Stream before use
	clearDebugStream();

	//While there are at least 100 bytes available in the buffer
	while(getAvailSpaceInDebugStream() >100)
	{
		//Write the value of the Sonar sensor to it
		writeDebugStreamLine("Analog pin test: %f", (SensorValue[gripperBumper]));
	  writeDebugStreamLine("Left Bumper test: %f", (SensorValue(BackLeftSwitch)));
	  writeDebugStreamLine("Right Bumper test: %f", (SensorValue(BackRightSwitch)));
		//writeDebugStreamLine("Value sharp IR sensor convert to cm: %f", (18000/(SensorValue[RightDistanceSensor]-100)));
		sleep(100);
	}

}
