#pragma config(Sensor, dgtl1,  startSwitch,    sensorTouch)
#pragma config(Motor,  port2,           leftWheel,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           rightWheel,    tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//---------------------------function definitions----------------------------------
void differnetial_drive (int leftLevel, int rightLevel);
//---------------------------tasks definitions------=------------------------------


/*--- differential drive -----
direction: 1 (forward), -1 (backward)
speedMode: 0(stop), 1(1/4 speed),2,3,4(max speed), minus/plus sign
*/
void differnetial_drive(int leftLevel, int rightLevel)
{
	int voltageRight;
	int voltageLeft;

	voltageLeft = leftLevel*30;
	voltageRight = rightLevel*30;

	motor[rightWheel] = voltageRight;
	motor[leftWheel]  = -voltageLeft;
}



void wait_for_on()
{
	while(SensorValue[startSwitch] == 0)
	{
		// while start switch not activated, wait inside the loop
	}
	differnetial_drive(1,1); // move straight ahead
	wait1Msec(1000);//wait one second
	differnetial_drive(1,-1);
	wait1Msec(1000);

	// button bushed, start the tasks (multi-tasking parallel thread)
	// startTask(competition);
	// startTask(emergency_stop);
}


/*------------------------------------------------------------------------------------------------------------------*/
/*------------------------------------Tasks (Parallel-runing programs (threads))------------------------------------*/
/*------------------------------------------------------------------------------------------------------------------*/
/*
task competition()
{
	startTask(detection);
	startTask(detection_others);

	start_move();

	while(true)
	{

	}//end of while true
}
*/


// main task
task main()
{
	wait_for_on();
	//while(true)
	//{
		// runing until told to stop
	//}
}//end of main
