#pragma config(Sensor, in1,    sharp1,         sensorAnalog)
#pragma config(Sensor, in2,    long1,          sensorAnalog)
#pragma config(Sensor, in3,    long2,          sensorAnalog)
#pragma config(Sensor, in4,    long3,          sensorAnalog)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//Opens Debug Stream Window automatically
#pragma DebuggerWindows("DebugStream")



task main()
{

//Clears Debug Stream before use
	clearDebugStream();

	//While there are at least 100 bytes available in the buffer
	while(getAvailSpaceInDebugStream() >100)
	{
		//Write the value of the Sonar sensor to it
		writeDebugStreamLine("Value sharp: %f", 4800/(SensorValue[in1]-20));
		writeDebugStreamLine("Value long 1: %f", 4800/(SensorValue[in2]-20));
		writeDebugStreamLine("Value long 2: %f", 4800/(SensorValue[in3]-20));
		writeDebugStreamLine("Value long 3: %f", 4800/(SensorValue[in4]-20));
		sleep(100);
	}

}
