#pragma config(Motor,  port2,           Left,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           Right,         tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Opens Debug Stream Window automatically
#pragma DebuggerWindows("DebugStream")



task main()
{

motor[port2] = 127;

wait1Msec(1000);



}
